### ISSUE TITLE
[ANT-651] Adaption for Antares Simulator v8.5 – new input and output

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1304]
---

## Problem Statement

On the new release of Antares Simulator v8.5 we have change in file settings/generaldata.ini, in section adequacy patch.
This properties are added : 

- **price-taking-order** [string] can take values DENS (default value) and Load.
- **include-hurdle-cost-csr** [bool]. Default value = false
- **check-csr-cost-function** [bool]. Default value = false
- **threshold-initiate-curtailment-sharing-rule** [double]. Default value = 0.0
- **threshold-display-local-matching-rule-violations** [double]. Default value = 0.0
- **threshold-csr-variable-bounds-relaxation** [int]. Default value = 3

In output files values-<period>.txt (mc-all & mc-ind), where the propertie **include-adq-patch** in settings/generaldata.ini file is set to true, those columns are added : 

- LMR VIOL.
- SPIL. ENRG. CSR
- DTG MRG CSR

## Proposed Solution

Antares Web must offer the possibility to users to active adequacy patch whom is in the simulator and modify the other new properties. And also to see new output on the results view.

## Developer Notes

- Actually the adequacy patch on simulations options is a R package not include in the simulator. this new one is embedded on the solver.

**Comment by flomnes** [comment]
Hi,
I suggest three tabs, because the adq patch computation is done in two steps. It would make sense to disable the 2 last tabs if the adequacy patch is disabled.

## General (v8.3.0+)
- `include-adq-patch` [bool]
## Local matching rule (v8.3.0+)
- `set-to-null-ntc-from-physical-out-to-physical-in-for-first-step` [bool]. Default value = true
- `set-to-null-ntc-between-physical-out-for-first-step` [bool]. Default value = true
## Curtailment sharing rule (v8.5.0+)
| Label | Type | Possible values | Default value | Description |
|---|---|---|---|---|
| `price-taking-order` | string | DENS, Load | DENS | Price taking order used in the quadratic objective function (hourly CSR problem) |
| `include-hurdle-cost-csr` | bool | true, false | false | Include normalized hurdle costs in the quadratic objective function (hourly CSR problem) |
| **ADVANCED** |  |  |  |  |
| `check-csr-cost-function` | bool | true, false | false | If set to `true`, discard the CSR solution if the CSR cost increases after the quadratic optimization |
| `threshold-initiate-curtailment-sharing-rule` | double | >= 0 | 0.0 | Threshold of unsupplied energy over all areas marked "inside adequacy patch". If the sum of unsupplied energy exceeds it, run the CSR for this hour. A higher value means the CSR will be run for fewer hours |
| `threshold-display-local-matching-rule-violations` | double | >= 0 | 0.0 | Threshold of (node balance - unsupplied energy). If exceeded for the hour & area, variable LMR. VIOL is set to 1. Otherwise it is set to 0. |
| `threshold-csr-variable-bounds-relaxation` | int | >= 0 | 3 | Relaxation of variable bounds for the quadratic hourly problem (10^-x) |

All these parameters can be found in section **adequacy patch** in file **settings/generaldata.ini**.

**Comment by laurent-laporte-pro** [comment]
N/A
