### ISSUE TITLE
[ANT-652] In "Reservoir Levels" the percentage data must be between 0 and 100 and we should have daily lines

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1329]
## Description
The labels in the “Time” column are daily data and not hourly data with 365 rows. It should therefore appear lines from 01/01 to 31/12 and not time slots.

## Steps to Reproduce
You can see this behavior in a study 1000MCY

## Actual Behavior
The data in Reservoir Levels is an number between 0 and 1 and the lines are in hourly 

## Expected Behavior
The data in Reservoir Levels must be in percentage between 0 and 100 and the line must be the day 1st January to 31 December.
 
## Screenshots
![hydro_reservoir_level](https://github.com/AntaresSimulatorTeam/AntaREST/assets/43534797/9b707a95-cd41-441b-b2fe-992c21174521)
![image](https://user-images.githubusercontent.com/114937156/220871297-b3522bd9-6dc7-46be-94be-2a5b1a741b5f.png)

## Possible Solution

If you have a solution in mind, describe it here.
## Environment

- [x] Production
- [x] Staging
### Add any other context about the problem here.

- If applicable, provide the study ID that this issue relates to: search a study name 1000MCY in staging

**Comment by laurent-laporte-pro** [comment]
Côté back office :

- Lecture des matrices : ajouter un flag "format=view" pour calculer les valeurs en pourcentage.
- Enregistrement des matrices : ajouter le même flag.

Au niveau de la lecture / écriture du FileStudyTree

**Comment by MartinBelthle** [comment]
On dev branch today, i do not see any problem concerning the column names. 
The starting date of the matrix corresponds to the value of the field `first-month-in-year` in the file`settings/generaldata.ini` as it is supposed to.
Also, the date is correctly formatted if I understand the issue correctly (see screenshot below)

![res_level](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/8b1786ba-28ab-47fb-b317-5eec3005ea8a)

So the only issue remaining is the percentage issue.

**Comment by laurent-laporte-pro** [comment]
Observed behavior in version v2.15.1:

- Decimal values between 0 and 1 are displayed instead of values between 0 and 100 (percentages).
- If a decimal value between 0 and 1 is entered in any of the three columns "Lev lov", "Lov Avg", or "Lev High", it is rounded down to the nearest integer number.
- If an integer value is entered, it is saved without validating its validity (range checking).
- The entered values are updated as-is in the matrix `/input/hydro/common/capacity/reservoir_{area_id}.txt`.

An application correction must be made to accommodate the following constraints:

- Values must be decimal numbers between 0 and 1 (inclusive).
- It is necessary to display at least 4 decimal places, for example, "0.1275".

> Note: Users do not have a strong request to display numbers as percentages. This constraint is therefore lifted; it is a nice-to-have feature.

**Comment by makdeuneuv** [comment]
to be done in sprint 25
