### ISSUE TITLE
[ANT-652] Update Hydro matrices

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1332]
## Description
The labels in the "Time" column of the "Hydro Storage" TS screen which are daily and not hourly data with 365 lines which in the screen below should therefore go from 01/07 to 30/06 and not from 01/07 00:00 to 16/07 04:00

## Screenshots
![image](https://user-images.githubusercontent.com/114937156/220882323-4cf2fb82-bc87-4c67-8a83-319225650266.png)
![image](https://user-images.githubusercontent.com/114937156/220882363-6c8cd19a-a930-4220-890c-4fd022b5ca50.png)

## Environment

- [x] Production
- [x] Staging

**Comment by hdinia** [comment]
Multiple matrices "Time" column need to be fixed
> TODO

- [x] The "Hydro storage" "Run of river", "Reservoir levels", "Water values" and "Energy credit" matrices should be Daily instead of Hourly (currently)
- Daily power: 
- [x] Change the matrix first column (without name) + 2 rows with label "Generating power" and "Pumping power
- [x] The name of the cols should be 0-100 instead of TS-n 
- Standard credit:
- [x] The Standard credit matrix in the Energy Credits tab should be Daily
- Water values:
- [x] The name of the cols should be 0%-100% instead of TS-n
- [x] Remove "Total" column
