### ISSUE TITLE
Error 500 when scanning directory

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1372]
## Description
When we need to scan a directory, we get an error 500.

## Screenshots
![image](https://user-images.githubusercontent.com/114937156/222738535-5e10eaa2-442d-4a98-b758-4a4fba200b24.png)

## Environment

- [x] Production
- [x] Staging

**Comment by makdeuneuv** [comment]
@laurent-laporte-pro Can you precise what's the version whom fixe this issue ? Because it's still present

**Comment by makdeuneuv** [comment]
Some precision about this issue


![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/6a3d5361-f6d1-4ea4-8ea4-3dee1d5192fc)

**Comment by MartinBelthle** [comment]
I have tested the scanner, and it is now fixed in the staging and integration environments but not in production. This is because the `dev` branch contains the fix, but the `master` branch does not. @laurent-laporte-pro, is there a specific reason for this?

**Comment by laurent-laporte-pro** [comment]
This issue was classified as a _bugfix_ rather than a _hotfix_, so the correction is currently only available in the `dev` branch. @makdeuneuv, should we reconsider the priority of this issue and treat it as "hot"? In that case, I will create a branch `hotfix/v2.14.5` to include the fix for this bug. See #1654
