### ISSUE TITLE
[ANT-706] Add Storages View

### ISSUE THREAD

**Issue by skamril** [AntaresSimulatorTeam/AntaREST#1515]
See ANT-706 on JIRA for the detailed description up to date.

![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/1954121/3c1af983-eb40-45f9-b7db-1e9dc6e134b3)

![Image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/1954121/04fb77f4-0f56-4dee-89c7-57710bcc9f64)

- [ ] Use DynamicDataTable to list storages
- [ ] Add ST Storage form
- [ ] Add the time-series below the forms

**Comment by makdeuneuv** [comment]
@skamril feedack from Jean-Marc(see comments on gopro page  https://gopro-collaboratif.rte-france.com/display/ANTR/Stockage+court+terme+pour+AntaresWeb )

On the first form : 
- replace "Injection nominal capacity" by  "Injection capacity"
- replace "Withdraw N. C." by "Withdrawal capacity"
- delete column "Storage units" because in this version there can only be one unit per ST Storage.

On second form : 
- Replace " SERIE TEMPORELLE x" with the wording of what this time series actually represents.
