### ISSUE TITLE
Unhandled exception when we close the systray application - antares desktop

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1575]
## Description
Since v2.14.2 of Antares Web Desktop on Windows, when we close the application we get this error message : 

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/dde27349-6a64-42d5-a2ab-063c9ace79e7)

```python
Traceback (most recent call last):
  File "env.py", line 17, in <module>
AttributeError: module 'alembic.context' has no attribute 'config'
```

## Steps to reproduice

1. Go to the icon in the bottom right corner of the Windows bar
![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/c4e29899-f6d1-4cbd-a50a-9a46aebafc67)
2. Click right and select "Quit"
3. and you'll get the error

**Comment by laurent-laporte-pro** [comment]
See: https://stackoverflow.com/questions/51203641/attributeerror-module-alembic-context-has-no-attribute-config

`alembic.context` is only available for the `env.py` script when it is executed through the `alembic` command, and provided that the `alembic` command is executed from a folder containing an `alembic.ini` file specifying the Alembic configuration to use.

Otherwise, the `alembic` module does not have a `context` property.

For more information, see [this answer to a similar question][1].

  [1]: https://stackoverflow.com/a/46050669/939364
