### ISSUE TITLE
Impossible to see some matrix file in output

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1659]
## Description

After run a simulation in 1 MC year and synthesis and year-by-year output, I can't see in results view this matrix : 

- id-<period>.txt
- values-<period>.txt

I got the message below and associates files are present in the output folder

![image](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/e3f3cfc2-d050-4e6b-83eb-5cb3f74498f1)

When associates files are not presents I got the right message "no data available"
Also see in study version 8.4.2 .

**Comment by MartinBelthle** [comment]
Indeed, this is due to this PR : https://github.com/AntaresSimulatorTeam/AntaREST/pull/1577, because now the JsonResponse doesn't allow Nan values (file raw_studies_blueprint.py, endpoint `GET /studies/uuid/raw`), so the code raises an Exception. According to the code documentation, there is a reason to it but I do not understand why you made that change @laurent-laporte-pro  ?

**Comment by laurent-laporte-pro** [comment]
If I understand the user's expectation correctly, this view should display a result matrix containing NaN values. Technically, to display a value table in TSV format, we use a transformation that utilizes JSON format. This format has a limitation: it cannot represent NaN values, just like infinite values. What I don't understand is why the results contain NaN values. One solution would be to replace the invalid values with the strings: 'NaN' '+Inf' and '-Inf'.

**Comment by MartinBelthle** [comment]
I discussed with Laurent and it seems that this issue has been resolved with this PR : https://github.com/AntaresSimulatorTeam/AntaREST/pull/1577 thanks to this commit : https://github.com/AntaresSimulatorTeam/AntaREST/commit/8204d45867f54337306d463e217ae259b3cc761f

**Comment by MartinBelthle** [comment]
On the 28/08 i encountered the issue again on `dev` branch. I created a v8.5 study with one area and i launched it. The simulator returned NaN values for hydro level and other columns (which is normal as i did not register any info about hydro in my area). But when i go in the front-end, in the results view i cannot see the matrix. Going to the DEBUG view raises this comment : 

``` 
ValueError: Out of range float values are not JSON compliant
```
This comes from line 149 in file `raw_studies_blueprint.py` : 
``` python
return JSONResponse(content=output)
```
This is due to the NaN values in the matrix so i reopen this issue
