### ISSUE TITLE
[ANT-868] Make study launch view more ergonomic and easy to use

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1781]
## Problem Statement

The current launch view presents some problems: presence of options which are no longer used (Xpansion R and linearized adequacy patch R), too many actions to launch the adequacy patch R which means that some are forgotten. Thus wasting users' time because in this case, they have to restart the processing again.

## Proposed Solution
First, modify the launch view so that the settings are easy to manipulate (see screnshot)
![image-2023-8-25_16-8-21](https://github.com/AntaresSimulatorTeam/AntaREST/assets/114937156/5be929c1-fb56-4ff3-b5c5-09ba1db7244f)

Then secondly, remove the obsolete options (it's will be specify soon in another issue)

**Comment by laurent-laporte-pro** [comment]
## Description des évolutions (version 1)

### Suppression du Libellé "Options"

- Le libellé "Options" sera supprimé car il est implicite et ne contribue pas à la compréhension de la boîte de
  dialogue.

### Réorganisation des Paramètres Généraux

- Les paramètres généraux seront simplifiés et regroupés sur une seule ligne pour économiser de l'espace.
- La taille du champ "Limite de temps" sera réduite.
- Le champ "Limite de temps" ne doit pas prendre une valeur supérieure à 240 (heures)
- Le champ "Nombre de cœurs" sera remplacé par un champ de type input avec les propriétés suivantes : min=1, max=24,
  default=22.
- Le champ "Charge du cluster" sera supprimé car il est redondant.

### Création du Bloc "Simulateur"

- Un bloc "Simulateur" sera créé pour regrouper les paramètres liés au simulateur, rendu bien visible (par exemple,
  encadré).
- Les champs suivants seront placés sur une même ligne :
  - Libellé "Simulateur".
  - Liste déroulante "Version".
  - Case à cocher "Xpress".
- Sur une autre ligne, les éléments suivants seront affichés :
  - Case à cocher "Adequacy Patch R" (le libellé doit être ajusté pour spécifier clairement qu'il s'agit de la version
    R).
  - Case à cocher "Dézippage automatique".
- Sur une dernière ligne, un champ "Autres Options" sera inclus.

### Création du Bloc "Xpansion"

- Un bloc "Xpansion" sera créé pour regrouper les paramètres liés à Xpansion, également bien visible (par exemple,
  encadré).
- Les champs suivants seront placés sur une même ligne :
  - Case à cocher "Xpansion".
  - Liste déroulante "Version d'Xpansion" permettant de choisir entre les versions R et C++.
- Sur une autre ligne, les éléments suivants seront inclus :
  - Case à cocher "Analyse de sensibilité".
  - Liste déroulante "Sélectionnez une sortie".

### Règles de gestion

- Le champ "Adequacy Patch non linéarisé" doit être coché lorsque la case "Adequacy Patch R" est cochée.
- Le champ "Autres Options" doit être automatiquement rempli avec la valeur "adq_patch_rc" lorsque la case "Adequacy
  Patch R" est cochée.
- Le champ "Version" doit par défaut pointer sur celle de l'étude.
- Le champ "Xpress" doit par défaut être désactivé.

**Comment by tbittar** [comment]
Comme les utilisateurs n'utilisent plus la version R d'Xpansion, la "Liste déroulante "Version d'Xpansion" permettant de choisir entre les versions R et C++." est inutile, seule la version C++ doit pouvoir être lancée.

**Comment by hdinia** [comment]
#### Quick Rework Possibility:
We can certainly perform a quick and "dirty" rework to solve the immediate problems such as removing unused options, simplifying the General Settings, and reorganizing parameters into more meaningful groups like "Simulator" and "Xpansion". These changes will be more like a patch to improve the user experience in the short term by reducing unnecessary complexity and making the launch view more intuitive.

**There's a PR coming soon to address all these problems.**

#### Need for Comprehensive Redesign:
However, it’s crucial to highlight that this component, LauncherDialog, genuinely needs a comprehensive redesign and refactor. The form is currently old, relies heavily on the state to manage inputs, and suffers from performance issues due to multiple endpoints fetching data.

#### Technical Work Required:

State Management: Transitioning from a state-heavy design to a more modern approach (react-hook-form).

API Endpoints: Consolidating multiple endpoints into a dedicated one, simplifying the data fetching process, and potentially improving load times and responsiveness.

Code Refactoring: General code cleanup and modularization.

See new issue: #1783 
@laurent-laporte-pro @makdeuneuv
