### ISSUE TITLE
Cannot delete 2 areas in a row

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/AntaREST#2091]
## Description

Provide a clear and concise description of the issue.
### Steps to reproduce the behavior:
1. Go to whatever managed study that contains at least 2 areas, on a variant
2. Click on an area, remove it
3. Click on another area, remove it

![image](https://github.com/user-attachments/assets/52d83ab1-4e99-4210-b373-3e7f9d35085a)

```
Status : 417
Exception : VariantGenerationError
Description :
Error while generating 440f95c0-1693-4aea-8c56-afce8cee9505
```

## Possible Solution

If you have a solution in mind, describe it here.
## Environment

- [ ] Production
- [X] Staging
## Additional Information

After closing the variant, and opening it again, the following error appears
![image](https://github.com/user-attachments/assets/cad0778e-aa06-4ca7-8605-917fc9cd0f23)

### Add any other context about the problem here.

- If applicable, provide the study ID that this issue relates to: 40f95c0-1693-4aea-8c56-afce8cee9505
- Any relevant logs or error messages: NONE
- Any relevant code snippets: NONE
- Any relevant library versions: NONE
- The date and time when the issue occurred: 15/07/2024
- Browser and version: Firefox 107.0
- Operating System: Ubuntu 20.04

**Comment by MartinBelthle** [comment]
I did not finish the investigation but the bug can be reproduced by removing only one area.
Also, the same thing happens for the raw parent study. 
The issue comes from the fact that the given study is in mode "aggregated" and not "clusters". We should handle such a case, I'll fix it.
It's fixed I'll add a test and a PR linked to this issue.
