### ISSUE TITLE
Add a support/help button

### ISSUE THREAD

**Issue by pl-buiquang** [AntaresSimulatorTeam/AntaREST#470]
The button should be displayed in fixed on the right bottom of the page with text : "Signal a bug".
It should open a popover displaying a contact mail and short guideline to describe the issue.

**Comment by laurent-laporte-pro** [comment]
It can be relevant to have a form for reporting bugs in a web application, as it allows users to effectively and centrally report issues they encounter. It can also help improve the user experience by allowing users to report issues without having to leave the application or search for how to contact support.

The bug report form could include fields such as:

-   a detailed description of the bug
-   screenshots or videos to show the bug
-   a category to classify the type of bug (such as a bug, data error, feature request)
-   a field to attach relevant files (such as debugging logs)
-   a field to indicate the URL or page where the bug occurred
-   a field to indicate the version of the application being used
-   a field for the user identification (email, username, etc)

By having a bug report form, developers and support teams can easily identify and reproduce issues reported by users, allowing for faster resolution and improving the application.

It's important to note that the bug report form should be easy to find and use, and it should include clear instructions for users on how to report an issue. Additionally, it's important to have a tracking system for reported issues, so that users can be informed about the status of their reported issues.

> **NOTE:** Ideally, we would use the JIRA API to create a ticket directly in JIRA and notify users.
